version: '3.9'

networks:
  hanzo-network:
    external: true

services:
  backend:
    image: ghcr.io/blockscout/blockscout:${DOCKER_TAG:-latest}
    container_name: 'zoonet-backend'
    restart: always
    stop_grace_period: 5m
    command: "bin/blockscout start"
    networks:
      - hanzo-network
    ports:
      - "4001:4000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./docker-compose/envs/common-blockscout.env
    environment:
      ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:9650/ext/bc/bXe2MhhAnXg6WGj6G8oDk55AKT1dMMsN72S8te7JdvzfZX1zM/rpc
      ETHEREUM_JSONRPC_TRACE_URL: http://host.docker.internal:9650/ext/bc/bXe2MhhAnXg6WGj6G8oDk55AKT1dMMsN72S8te7JdvzfZX1zM/rpc
      ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:9650/ext/bc/bXe2MhhAnXg6WGj6G8oDk55AKT1dMMsN72S8te7JdvzfZX1zM/ws
      CHAIN_ID: '200008'
      DATABASE_URL: postgresql://blockscout:blockscout@lux-postgres:5432/explorer_zoonet?sslmode=disable
      DISABLE_MIGRATE: 'false'

  frontend:
    image: ghcr.io/blockscout/frontend:${FRONTEND_TAG:-latest}
    container_name: 'zoonet-frontend'
    restart: always
    networks:
      - hanzo-network
    depends_on:
      - backend
    ports:
      - "3001:3000"
    env_file:
      - ./docker-compose/envs/common-frontend.env
    environment:
      NEXT_PUBLIC_API_HOST: api-explore.zoo.network
      NEXT_PUBLIC_NETWORK_NAME: "ZOO Network"
      NEXT_PUBLIC_NETWORK_ID: 200008
      NEXT_PUBLIC_NETWORK_SHORT_NAME: ZOO
      NEXT_PUBLIC_NETWORK_CURRENCY_NAME: ZOO
      NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL: ZOO
      NEXT_PUBLIC_IS_TESTNET: 'false'

  visualizer:
    image: ghcr.io/blockscout/visualizer:${VISUALIZER_VERSION:-latest}
    container_name: 'zoonet-visualizer'
    restart: always
    networks:
      - hanzo-network
    env_file:
      - ./docker-compose/envs/common-visualizer.env
    ports:
      - "8260:8050"

  sig-provider:
    image: ghcr.io/blockscout/sig-provider:${SIG_PROVIDER_VERSION:-latest}
    container_name: 'zoonet-sig-provider'
    restart: always
    networks:
      - hanzo-network
    ports:
      - "8261:8050"

  stats:
    image: ghcr.io/blockscout/stats:${STATS_VERSION:-latest}
    container_name: 'zoonet-stats'
    restart: always
    networks:
      - hanzo-network
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./docker-compose/envs/common-stats.env
    environment:
      STATS__DB_URL: postgresql://blockscout:blockscout@lux-postgres:5432/stats_zoonet?sslmode=disable
      STATS__BLOCKSCOUT_DB_URL: postgresql://blockscout:blockscout@lux-postgres:5432/explorer_zoonet?sslmode=disable
      STATS__CREATE_DATABASE: 'false'
      STATS__RUN_MIGRATIONS: 'false'
    ports:
      - "8263:8050"