version: '3.9'

networks:
  hanzo-network:
    external: true

services:
  backend:
    image: ghcr.io/blockscout/blockscout:${DOCKER_TAG:-latest}
    container_name: 'luxtest-backend'
    restart: always
    stop_grace_period: 5m
    command: "bin/blockscout start"
    networks:
      - hanzo-network
    ports:
      - "4010:4000"
    extra_hosts:
      - "k8s-host:192.168.1.99"
      - "host-postgres:192.168.1.99"
      - "host-redis:192.168.1.99"
    env_file:
      - ./docker-compose/envs/common-blockscout.env
    environment:
      ETHEREUM_JSONRPC_HTTP_URL: http://k8s-host:9650/ext/bc/2sdADEgBC3NjLM4inKc1hY1PQpCT3JVyGVJxdmcq6sqrDndjFG/rpc
      ETHEREUM_JSONRPC_TRACE_URL: http://k8s-host:9650/ext/bc/2sdADEgBC3NjLM4inKc1hY1PQpCT3JVyGVJxdmcq6sqrDndjFG/rpc
      ETHEREUM_JSONRPC_WS_URL: ws://k8s-host:9650/ext/bc/2sdADEgBC3NjLM4inKc1hY1PQpCT3JVyGVJxdmcq6sqrDndjFG/ws
      CHAIN_ID: '96368'
      DATABASE_URL: postgresql://blockscout:ceWb1MeLBEeOIfk65gU8EjF8@host-postgres:5432/explorer_luxtest?sslmode=disable
      DISABLE_MIGRATE: 'true'

  frontend:
    image: ghcr.io/blockscout/frontend:${FRONTEND_TAG:-latest}
    container_name: 'luxtest-frontend'
    restart: always
    networks:
      - hanzo-network
    depends_on:
      - backend
    ports:
      - "3010:3000"
    env_file:
      - ./docker-compose/envs/common-frontend.env
    environment:
      NEXT_PUBLIC_API_HOST: localhost:4010
      NEXT_PUBLIC_NETWORK_NAME: "LUX Testnet"
      NEXT_PUBLIC_NETWORK_ID: 96368
      NEXT_PUBLIC_NETWORK_SHORT_NAME: LUX
      NEXT_PUBLIC_NETWORK_CURRENCY_NAME: LUX
      NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL: LUX
      NEXT_PUBLIC_IS_TESTNET: 'true'

  visualizer:
    image: ghcr.io/blockscout/visualizer:${VISUALIZER_VERSION:-latest}
    container_name: 'luxtest-visualizer'
    restart: always
    networks:
      - hanzo-network
    env_file:
      - ./docker-compose/envs/common-visualizer.env
    ports:
      - "8150:8050"

  sig-provider:
    image: ghcr.io/blockscout/sig-provider:${SIG_PROVIDER_VERSION:-latest}
    container_name: 'luxtest-sig-provider'
    restart: always
    networks:
      - hanzo-network
    ports:
      - "8151:8050"

  stats:
    image: ghcr.io/blockscout/stats:${STATS_VERSION:-latest}
    container_name: 'luxtest-stats'
    restart: always
    networks:
      - hanzo-network
    depends_on:
      - backend
    extra_hosts:
      - "k8s-host:192.168.1.99"
      - "host-postgres:192.168.1.99"
      - "host-redis:192.168.1.99"
    env_file:
      - ./docker-compose/envs/common-stats.env
    environment:
      STATS__DB_URL: postgresql://blockscout:ceWb1MeLBEeOIfk65gU8EjF8@host-postgres:5432/stats_luxtest?sslmode=disable
      STATS__BLOCKSCOUT_DB_URL: postgresql://blockscout:ceWb1MeLBEeOIfk65gU8EjF8@host-postgres:5432/explorer_luxtest?sslmode=disable
      STATS__CREATE_DATABASE: 'false'
      STATS__RUN_MIGRATIONS: 'false'
    ports:
      - "8153:8050"