version: '3.9'

services:
  # redis-db:
  #   extends:
  #     file: ./services/redis.yml
  #     service: redis-db

  # db-init:
  #   extends:
  #     file: ./services/db.yml
  #     service: db-init

  # db:
  #   extends:
  #     file: ./services/db.yml
  #     service: db

  backend:
    # depends_on:
    #   - db
    #   - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        RELEASE_VERSION: 8.1.1
    # links:
    #   - db:database
    command: "bin/blockscout start"
    ports:
      - "4000:4000"
    extra_hosts:
      - "k8s-host:192.168.1.99"
      - "host-postgres:192.168.1.99"
      - "host-redis:192.168.1.99"
    environment:
        ETHEREUM_JSONRPC_HTTP_URL: http://k8s-host:9650/ext/bc/dnmzhuf6poM6PUNQCe7MWWfBdTJEnddhHRNXz2x7H6qSmyBEJ/rpc
        ETHEREUM_JSONRPC_TRACE_URL: http://k8s-host:9650/ext/bc/dnmzhuf6poM6PUNQCe7MWWfBdTJEnddhHRNXz2x7H6qSmyBEJ/rpc
        ETHEREUM_JSONRPC_WS_URL: ws://k8s-host:9650/ext/bc/dnmzhuf6poM6PUNQCe7MWWfBdTJEnddhHRNXz2x7H6qSmyBEJ/ws
        CHAIN_ID: '96369'
        DISABLE_INDEXER: 'true'
        DISABLE_REALTIME_INDEXER: 'true'
        DISABLE_CATCHUP_INDEXER: 'true'
        INDEXER_DISABLE_TOKEN_INSTANCE_FETCHER: 'true'
        INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'true'
        INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: 'true'

  nft_media_handler:
    depends_on:
      - backend
    extends:
      file: ./services/nft_media_handler.yml
      service: nft_media_handler
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        RELEASE_VERSION: 8.1.1
    extra_hosts:
      - "k8s-host:192.168.1.99"
      - "host-postgres:192.168.1.99"
      - "host-redis:192.168.1.99"

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend

  # stats-db-init:
  #   extends:
  #     file: ./services/stats.yml
  #     service: stats-db-init

  # stats-db:
  #   depends_on:
  #     stats-db-init:
  #       condition: service_completed_successfully
  #   extends:
  #     file: ./services/stats.yml
  #     service: stats-db

  stats:
    depends_on:
      # - stats-db
      - backend
    extends:
      file: ./services/stats.yml
      service: stats
    extra_hosts:
      - "k8s-host:192.168.1.99"
      - "host-postgres:192.168.1.99"
      - "host-redis:192.168.1.99"

  user-ops-indexer:
    depends_on:
      # - db
      - backend
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer
    extra_hosts:
      - "k8s-host:192.168.1.99"
      - "host-postgres:192.168.1.99"
      - "host-redis:192.168.1.99"

  # proxy:
  #   depends_on:
  #     - backend
  #     - frontend
  #     - stats
  #   extends:
  #     file: ./services/nginx.yml
  #     service: proxy
